const notes = {
  "12_10": [
    "- The GPG key used to sign the GitLab packages was changed on April 6, 2020. If you had configured the GitLab package repositories on your machines prior to that, you will need to take some manual steps to add the new key before you can install or update GitLab packages. See the [Omnibus Improvements](#omnibus-improvements) for more details.",
    "- PostgreSQL 11 is the default version of PostgreSQL in GitLab 12.10. All new installs of GitLab will automatically default to PostgreSQL 11. For upgrades of existing GitLab installations, the PostgreSQL version will be automatically upgraded to PostgreSQL 11 if PostgreSQL 9.6 or 10 are detected. However, major PostgreSQL upgrades on installations with High Availability and/or Geo require some manual steps. If GitLab detects that you are using repmgr or Geo, it will ask you to follow the manual upgrade instructions [for HA](https://docs.gitlab.com/omnibus/settings/database.html#upgrading-a-gitlab-ha-cluster) or [for Geo](https://docs.gitlab.com/omnibus/settings/database.html#upgrading-a-geo-instance); we will not automatically upgrade your PostgreSQL database. For 12.10, if you prefer to upgrade your GitLab version first and upgrade PostgreSQL later, you still have the option to stay on PostgreSQL 9.6 or 10 by disabling the PostgreSQL upgrade before you upgrade GitLab (`sudo touch /etc/gitlab/disable-postgresql-upgrade`). **Note**: There is a known issue when upgrading to 12.10 when using an external PostgreSQL database rather than the Omnibus-packaged database, resulting in the need to take some manual steps. To track this bug and see the workaround refer to the [related issue](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5299).",
    "",
    "    Please note that PostgreSQL 9.6 and 10 will be removed in the next version of GitLab (13.0). This means that you will need to upgrade your PostgreSQL database to PostgreSQL 11 before you can upgrade to GitLab 13.0. We are very excited about the database performance improvements that PostgreSQL 11 will allow us to make and look forward to sharing the benefits of these improvements with you over the coming months.",
  ],
  "12_8": [],
  "12_9": [
    "- GitLab 12.9 includes Mattermost 5.20. For important upgrade notes on upgrading to this latest version of Mattermost, see [Important Upgrade Notes](https://docs.mattermost.com/administration/important-upgrade-notes.html).",
    "- GitLab 12.9 has a new command for checking background migrations. This is important for zero-downtime upgrades. For details, see [Updating GitLab](https://docs.gitlab.com/ee/update/README.html#checking-for-background-migrations-before-upgrading).",
  ],
  "13_0": [
    "- Before upgrading to GitLab 13.0, you will need to upgrade to 12.10. For more details on upgrading, see [Upgrading to a new major version](https://docs.gitlab.com/ee/update/#upgrading-to-a-new-major-version).",
    "- GitLab 13.0 automatically migrates all snippets, creating a repository for each one of them and also committing a file into it based on the snippet `file name` and `content`. This operation is done in a background migration, therefore no downtime is required. In case the background migration fails migrating any of the snippets, GitLab 13.0 also introduces several [rake tasks](https://docs.gitlab.com/ee/raketasks/migrate_snippets.html) to help migrating them manually.",
    "- PostgreSQL 11 is the minimum required version starting in GitLab 13.0. PostgreSQL 9.6 and 10 have been removed and are no longer officially supported. You will need to plan on some downtime for the PostgreSQL upgrade because the database must be down while the upgrade is performed. If you are using the GitLab-provided PostgreSQL database, you should make sure that your database is PostgreSQL 11 on GitLab 12.10 regardless of your installation method.",
    "- Puma is now the default web application server for GitLab. Users who have customized their Unicorn settings will need to [manually migrate these settings to Puma](https://docs.gitlab.com/omnibus/settings/puma.html#configuring-puma-settings). Additionally installations using [Direct Git Access](https://docs.gitlab.com/ee/administration/gitaly/#direct-git-access-in-gitlab-rails), usually those with slower NFS drives, may want to consider [running Puma single-threaded](https://docs.gitlab.com/ee/administration/operations/puma.html#performance-caveat-when-using-puma-with-rugged). To learn more about the benefits of switching to Puma, see [the Puma release note](#reduced-memory-consumption-of-gitlab-with-puma). Unicorn support will be [removed in GitLab 14.0](#unicorn-will-be-removed-in-favor-of-puma).",
    "- If you are running a self-managed instance of GitLab with an external PostgreSQL database, please note that the default timeout for PostgreSQL statements that was [added in GitLab 12.9](/releases/2020/03/22/gitlab-12-9-released/#omnibus-improvements) has been temporarily disabled. This was due to [an issue experienced with GitLab.com](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5287). The default timeout will be re-enabled when [the proposed change in implementation has been added](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5255).",
    "- If you have a self-managed instance of GitLab and are using the Mattermost integration, please note that a schema change was made in the Mattermost database to fix performance issues with emoji reactions. As a result of the schema change, you may experience longer upgrade times if your Mattermost database contains a lot of emoji reactions. See [the Mattermost upgrade documentation](https://docs.mattermost.com/administration/important-upgrade-notes.html) for the recommended approach to upgrading.",
    "- The Redis configuration has been changed in 13.0 to replace the `slave` terminology with `replica`, and the Redis version was updated to 5.0.9. These change require a restart of Redis. If you are using Redis HA, follow the [Redis HA updgrade steps](https://gitlab.com/gitlab-com/www-gitlab-com/-/merge_requests/48907) to upgrade without downtime. If you are running Redis on a single node, you will need to plan on Redis being in accessbile while it restarts.",
  ],
  "13_1": [
    "- Before upgrading to GitLab 13.1, you must upgrade to GitLab 13.0, or — if you are using the Helm chart install — to the 4.0 version of the chart. For more information on recommended upgrade paths, see the [Upgrade recommendations](https://docs.gitlab.com/ee/policy/maintenance.html#upgrade-recommendations).",
  ],
  "13_10": [],
  "13_11": [],
  "13_12": [],
  "13_2": [
    '- GitLab 13.2.0 [remediates](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35492) an [email verification bypass](https://about.gitlab.com/releases/2020/05/27/security-release-13-0-1-released/). After upgrading, if some of your users are unexpectedly encountering 404 or 422 errors when signing in, or "blocked" messages when using the command line, their accounts may have been un-confirmed. In that case, please ask them to check their email for a re-confirmation link.',
    "- GitLab installations that have multiple web application nodes must be upgraded to 13.1 before they can be upgraded to 13.2. This is due to a breaking change in Rails that can result in authorization issues if this upgrade path is not followed. For details, [see this issue](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33454). For information about upgrading, see the [version-specific upgrade instructions](https://docs.gitlab.com/ee/update/README.html#1320).",
  ],
  "13_3": [],
  "13_4": [],
  "13_5": [
    "- An issue has been discovered affecting some instances, where the upgrade to `13.5.0` generates [an assertion error](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5743). This has been resolved in `13.5.1`.",
    "- The default path for the Workhorse socket changed from `/var/opt/gitlab/workhorse/socket` to `/var/opt/gitlab/workhorse/sockets/socket` in 13.5. A `gitlab-ctl reconfigure` is required during upgrade to apply this change. If you use SELinux and have specified a custom socket path, see the [upgrade documentation](https://docs.gitlab.com/ee/update/#1350) for some manual steps that are required.",
    "- [The Puma Worker Killer RAM limits were raised](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45116) to avoid frequent out of memory kills. This change can result in memory increase of around 20% on web nodes.",
    "- An issue was discovered in [instance merge request approvals](https://docs.gitlab.com/ee/user/admin_area/merge_requests_approvals.html#merge-request-approval-rules) that affects self-managed users on versions `13.2.0` to `13.5.3`. It allows project maintainers to modify MR approval rules even when an admin enabled the instance-level settings that are supposed to make the respective project settings read-only. We've [deployed a fix](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46637) to address this in `13.5.4` and later versions.",
  ],
  "13_6": [
    "- For users of the GitLab helm chart, [resource requests have been increased](#gitlab-chart-improvements) to better represent the amount consumed under load. We encourage administrators to review the changes and ensure their cluster has sufficient headroom, or services may fail to start.",
    "- Ruby 2.7.2 is now required. Users of source installs will need to",
    "  install GitLab with Ruby 2.7.2, or GitLab will not start. This is",
    "  already handled for GitLab Omnibus and Helm Chart users.",
  ],
  "13_7": [
    "- GitLab Helm chart deployments will experience a brief outage during the upgrade to 13.7. [This is due to a change to the way Webservice deployments are managed](https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/1642), which causes older deployments to be destroyed before new deployments are created. This will only occur for this release, as the charts move to this new method.",
    "- For users of the [GitLab helm chart](https://docs.gitlab.com/charts/), a new secret has been added to support [encrypted credentials](https://docs.gitlab.com/ee/administration/encrypted_configuration.html). If you have disabled the [shared-secrets chart](https://docs.gitlab.com/charts/charts/shared-secrets/), you will need to [manually create this secret](https://docs.gitlab.com/charts/installation/secrets.html#gitlab-rails-secret) by GitLab 14.0, when it will become required.",
  ],
  "13_8": [],
  "13_9": [],
  "14_0": [
    "- **Update**: You must upgrade to the **latest patch release of GitLab 14 (14.0.Z)**. This is required because at least two patch releases contain batched background migrations as part of our ongoing effort to [address primary key event overflow risks](https://gitlab.com/groups/gitlab-org/-/epics/5655). These background migrations have to finish before upgrading to a later version of GitLab. Consult the required [GitLab upgrade path](https://docs.gitlab.com/ee/update/#upgrade-paths) for more information.",
    "- Before upgrading to GitLab 14.0, you will need to upgrade to 13.12. For more details on upgrading, see [Upgrading to a new major version](https://docs.gitlab.com/ee/update/#upgrading-to-a-new-major-version).",
    "- You **must** upgrade to PostgreSQL 12 before upgrading to GitLab 14.0. PostgreSQL 12 is the minimum required version starting in GitLab 14.0. PostgreSQL 11 has been removed and is no longer officially supported. You will need to plan on some downtime for the PostgreSQL upgrade because the database must be down while the upgrade is performed. If you are using the GitLab-provided PostgreSQL database, you should make sure that your database is PostgreSQL 12 on GitLab 13.12 regardless of your installation method.",
    "- Multi-node database instances will need to switch from [repmgr to Patroni](https://docs.gitlab.com/ee/administration/postgresql/replication_and_failover.html#switching-from-repmgr-to-patroni), prior to [upgrading PostgreSQL with Patroni](https://docs.gitlab.com/ee/administration/postgresql/replication_and_failover.html#upgrading-postgresql-major-version-in-a-patroni-cluster). Geo secondaries can then be [updated](https://docs.gitlab.com/omnibus/settings/database.html#upgrading-a-geo-instance) and re-synchronized.",
    "- Before upgrading to GitLab 14.0 you **must** [migrate fully to hashed storage](https://docs.gitlab.com/ee/administration/raketasks/storage.html#migrate-to-hashed-storage).",
    "- Before upgrading to GitLab 14.0 you **must** [migrate to Puma](https://docs.gitlab.com/ee/administration/operations/puma.html).",
    "- Remove old ElasticSearch migrations. By removing old ElasticSearch migrations, it will be easier to perform Advanced Search migrations when upgrading GitLab.",
    "- GitLab 14.0 will only support migrations from GitLab 13.12. All previous versions must be upgraded to GitLab 13.12 before [upgrading to GitLab 14.0, the GitLab's latest major version](https://docs.gitlab.com/ee/update/#upgrading-to-a-new-major-version), to [complete all ElasticSearch migrations](https://docs.gitlab.com/ee/update/#checking-for-pending-elasticsearch-migrations).",
  ],
  "14_1": [
    "GitLab 14.1 contains batched background migrations as part of our ongoing effort to [address primary key event overflow risks](https://gitlab.com/groups/gitlab-org/-/epics/5655). These background migrations have to finish before upgrading to a later version of GitLab. Read the [GitLab 14.1 update instructions](https://docs.gitlab.com/ee/update/#1410) for further guidance.",
  ],
  "14_2": [
    "- Before upgrading to GitLab 14.2, you **must** upgrade to either the **latest patch release of GitLab 14 (14.0.Z)** or the **latest patch release of GitLab 14.1 (14.1.Z)**. This is important because these releases contain batched background migrations as part of our ongoing effort to [address primary key event overflow risks](https://gitlab.com/groups/gitlab-org/-/epics/5655). These background migrations included in the specified prior releases **have to finish before upgrading to GitLab 14.2**. Read the [GitLab 14.2 update instructions](https://docs.gitlab.com/ee/update/#1420) for further guidance.",
    "- GitLab 14.2 contains long running background migrations that swap columns on tables potentially affected by primary key overflows. Read the [GitLab 14.2 update instructions](https://docs.gitlab.com/ee/update/#1420) for further guidance and to learn what tables are affected.",
  ],
  "14_3": [
    "- GitLab 14.3 contains post-deployment migrations that swap columns on tables potentially affected by primary key overflows. Read the [GitLab 14.3 update instructions](https://docs.gitlab.com/ee/update/#1430) for further guidance and to learn what tables are affected.",
    "- When there is a Horizontal Pod Autoscaler (HPA) controlling the desired number of Pods, we will not provide the `.spec.replicas` value. We expect from rolling out this change, there will be a 1-time behavior regression, where during the first upgrade on an existing chart install the `Replicaset` will reduce itself down to a single Pod temporarily, rather than the count of currently running Pods. This will fix itself after the HPA kicks in and rescales the deployment. The reason this change is being implemented is to ensure that Pod capacity is not reduced unnecessarily during chart upgrades, but instead Pods will continue to remain properly scaled during deployments.",
  ],
  "14_4": [],
  "14_5": [
    "- An extra step for finalizing background migration jobs over the `merge_request_diff_commits` table may result in extra time required during an upgrade to 14.5. Large instances with a large number of merge request diff commits, may be interested to perform an optional manual operation to save additional space. For more information, please check the [version-specific upgrading instructions for 14.5](https://docs.gitlab.com/ee/update/#1450).",
    "- The Task Runner pod is used to execute periodic housekeeping tasks within the GitLab application, and is often confused with the GitLab Runner. To remove confusion, the [Task Runner is renamed to Toolbox](https://gitlab.com/groups/gitlab-org/charts/-/epics/25) in GitLab 14.5. This results in the rename of the sub-chart `gitlab/task-runner` to `gitlab/toolbox`. The resulting pods are named according to the pattern `{{ .Release.Name }}-toolbox`, which often results in pods named `gitlab-toolbox`. You can locate them with the label `app=toolbox`.",
    "",
    "- Sidekiq deployments were changed from having a `-v1` suffix to `-v2`. Due to the deployment name changing, Sidekiq shutdown of the old pods and start of the new is handled by separate deployments, and as a result there could be a period of time during the upgrade where there are no Sidekiq pods running. Sidekiq works on asynchronous jobs, so impact might be a delay in background job processing like running new CI jobs and updating merge requests diffs. [We are implementing `podAntiAffinity`](https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/2227) in such way that allows to spread out Sidekiq pods across the cluster.",
  ],
  "14_6": [
    "- GitLab 14.6 includes all the migrations for Mattermost 6.0 as well as 6.1, and has longer migrations than typical for most Mattermost upgrades. Large instances should consult the [upgrade documentation for both 6.0 and 6.1](https://docs.mattermost.com/upgrade/important-upgrade-notes.html). The upgrade does not require any manual steps, but there are some suggestions in the upgrades notes on ways to reduce downtime of the Mattermost server during the upgrade.",
  ],
};
export default notes;
